### ISSUE TITLE
Doesn't work on El Capitan ?

### ISSUE THREAD

**Issue by fhorlaville** [insidegui/F3X#1]
Hi !
Thanks a lot for this ; unfortunately on El Capitan, it shows the drives but they're greyed out and the button never activates. I have tried running it as super user with the same results. Thanks!

<img width="748" alt="screen shot 2016-01-03 at 03 15 42" src="https://cloud.githubusercontent.com/assets/8877524/12077115/612b4f9a-b1c8-11e5-84e0-1c3beec25841.png">

**Comment by insidegui** [comment]
It's only designed to work with external SD cards, not internal or external hard drives / SSDs. Since It fills the drives with files to test them It would be disastrous to run It on the system HD...

**Comment by fhorlaville** [comment]
In this case it was an external USB stick, but thanks for the heads up!

**Comment by dlebu** [comment]
I experienced the same problem with an external SD card plugged directly in my macbook. The card was listed but greyed out.

**Comment by dlebu** [comment]
Nevermind, I had a permission error with my SD card. Everything works as expected.
